### ISSUE TITLE
Add Subdomain for rehnuma-api

### ISSUE THREAD

**Issue by aliirz** [codeforpakistan/rehnuma-api#5]

**Comment by SaqibHussain44** [comment]
need rehnuma-api.pehchaan.kpgov.tech to point to `3.229.133.126`

**Comment by schajee** [comment]
A record added 
NAME: rehnuma-api.pehchaan.kpgov.tech
VALUE: 3.229.133.126

**Comment by SaqibHussain44** [comment]
It looks good, Thank you.
Closing the issue
